spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-9jcfijv8.sql.tencentcdb.com:21559/chinese_poetry?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cod..tsl..M200

#mybatis-plus 设置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:com/careless/chinesepoetrytodatabase/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_UUID
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑删除字段
      logic-delete-field: isValid
      # 逻辑删除值
      logic-delete-value: 0
      logic-not-delete-value: 1
      # 表名前缀
      table-prefix: pss_
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true